always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = true
normalize_line_endings = "unix"
separate_kwargs_with_semicolon = true
whitespace_in_kwargs = false
